guard 'rspec', cmd: "bundle exec rspec",
      all_after_pass: false,
      all_after_fail: true do
  watch(%r{\Aspec/.+_spec\.rb\z})
  watch(%r{\Alib/(.+)\.rb\z})   { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec" }
end

notification :gntp